#!/bin/bash
# Download (or re-download) echarts vendor bundle into web/vendor/echarts/
# according to the version specified in web/vendor/echarts/VERSION.
#
# Usage:
#   ./tools/vendor-echarts.sh
#
# Behavior:
#   1. Read version from web/vendor/echarts/VERSION
#   2. Download echarts.min.js from jsdelivr (fallback to unpkg)
#   3. Write SHA256SUMS for audit (version, sha256, url)
#   4. Self-check via sha256sum -c
#
# Any failure aborts with non-zero exit.

set -e

cd "$(dirname "$0")/.."
VENDOR_DIR="web/vendor/echarts"
VERSION_FILE="${VENDOR_DIR}/VERSION"
TARGET="${VENDOR_DIR}/echarts.min.js"
SUMS="${VENDOR_DIR}/SHA256SUMS"

if [ ! -f "$VERSION_FILE" ]; then
    echo "[ERROR] $VERSION_FILE not found. Create it with a version number (e.g. 5.5.0)." >&2
    exit 1
fi

VERSION=$(head -1 "$VERSION_FILE" | tr -d '[:space:]')
if [ -z "$VERSION" ]; then
    echo "[ERROR] $VERSION_FILE is empty" >&2
    exit 1
fi

PRIMARY_URL="https://cdn.jsdelivr.net/npm/echarts@${VERSION}/dist/echarts.min.js"
FALLBACK_URL="https://unpkg.com/echarts@${VERSION}/dist/echarts.min.js"

echo "[INFO] Target version: ${VERSION}"
echo "[INFO] Downloading from: ${PRIMARY_URL}"

download() {
    local url="$1"
    local out="$2"
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL --max-time 60 -o "$out" "$url"
    elif command -v wget >/dev/null 2>&1; then
        wget -q -O "$out" "$url"
    else
        echo "[ERROR] Neither curl nor wget is available" >&2
        return 1
    fi
}

# 下载到临时文件，成功后再替换
TMP=$(mktemp -t echarts-vendor.XXXXXX)
trap 'rm -f "$TMP"' EXIT

if ! download "$PRIMARY_URL" "$TMP"; then
    echo "[WARN] Primary download failed, trying fallback: ${FALLBACK_URL}"
    if ! download "$FALLBACK_URL" "$TMP"; then
        echo "[ERROR] Both primary and fallback downloads failed" >&2
        exit 1
    fi
    USED_URL="$FALLBACK_URL"
else
    USED_URL="$PRIMARY_URL"
fi

# 完整性 sanity check: 必须是非空 JS 且大小在合理范围
if [ ! -s "$TMP" ]; then
    echo "[ERROR] Downloaded file is empty" >&2
    exit 1
fi
BYTES=$(wc -c < "$TMP" | tr -d ' ')
# echarts 5.x minified 通常约 900KB - 1.2MB，设置宽松下限 200KB 防止下到错误页
if [ "$BYTES" -lt 204800 ]; then
    echo "[ERROR] Downloaded file is too small (${BYTES} bytes); aborting." >&2
    exit 1
fi
if ! grep -Eq 'echarts|ECharts|apache' "$TMP" ; then
    echo "[ERROR] Downloaded file does not contain echarts signatures; aborting." >&2
    exit 1
fi

# 计算 sha256（兼容 Linux coreutils、macOS shasum、macOS/BSD sha256sum）
compute_sha256() {
    local f="$1"
    if command -v sha256sum >/dev/null 2>&1; then
        # GNU coreutils: "<sha>  <file>"；macOS/BSD sha256sum: "SHA256 (file) = <sha>"
        local raw
        raw=$(sha256sum "$f" 2>/dev/null)
        if [[ "$raw" =~ ^([0-9a-fA-F]{64}) ]]; then
            echo "${BASH_REMATCH[1]}"
            return 0
        fi
        if [[ "$raw" =~ =[[:space:]]+([0-9a-fA-F]{64}) ]]; then
            echo "${BASH_REMATCH[1]}"
            return 0
        fi
    fi
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$f" | awk '{print $1}'
        return 0
    fi
    echo "[ERROR] No sha256 tool available (need sha256sum or shasum)" >&2
    return 1
}

verify_sha256() {
    local f="$1"
    local expected="$2"
    local actual
    actual=$(compute_sha256 "$f") || return 1
    if [ "$actual" != "$expected" ]; then
        echo "[ERROR] SHA256 mismatch for $f" >&2
        echo "[ERROR]   expected: $expected" >&2
        echo "[ERROR]   actual:   $actual" >&2
        return 1
    fi
    return 0
}

SHA=$(compute_sha256 "$TMP") || exit 1

mkdir -p "$VENDOR_DIR"
mv "$TMP" "$TARGET"
trap - EXIT

# 写入 SHA256SUMS
cat > "$SUMS" <<EOF
# echarts vendor bundle
# version: ${VERSION}
# source:  ${USED_URL}
# regenerated by tools/vendor-echarts.sh
${SHA}  echarts.min.js
EOF

# 自检
verify_sha256 "$TARGET" "$SHA" || exit 1

SIZE=$(wc -c < "$TARGET" | tr -d ' ')
echo ""
echo "========================================="
echo "[OK] echarts ${VERSION} vendored"
echo "  Path:   ${TARGET}"
echo "  Size:   ${SIZE} bytes"
echo "  SHA256: ${SHA}"
echo "  Source: ${USED_URL}"
echo ""
echo "  Remember to: git add ${VENDOR_DIR}/{VERSION,echarts.min.js,SHA256SUMS}"
echo "               update CHANGELOG under [Unreleased] Security or Changed"
echo "========================================="
